  [[main]]
  name = "home"
  identifier = "home"
  weight = 100
  url = "/about/"

  [[main]]
  name = "teaching"
  weight = 200
  identifier = "teaching"
  url = "/teaching/"

  [[main]]
  name = "talks"
  weight = 300
  identifier = "talks"
  url = "/talks/"

  [[main]]
  name = "publications"
  weight = 400
  identifier = "publications"
  url = "/publications/"
  
  [[main]]
  name = "blog"
  weight = 500
  identifier = "blog"
  url = "https://corpling.hypotheses.org/"

  [[main]]
  name = "contact"
  weight = 500
  identifier = "contact"
  url = "/contact/"

  [[footer]]
  name = "my HAL CV"
  weight = 1
  identifier = "madewith"
  url = "https://cv.archives-ouvertes.fr/guillaume-desagulier"